### ISSUE TITLE
Error using icon with groovyfx

### ISSUE THREAD

**Issue by shnplr** [griffon-plugins/griffon-silkicons-plugin#1]
When configuring silkIcin in messages.properties as per the guide I receive the following error:

java.lang.RuntimeException: Failed to create component for 'button' reason: griffon.core.editors.ValueConversionException: Can't convert 'griffon.javafx.support.silk.SilkIcon|star' into javafx.scene.Node

The documentation indicates that:
The griffon-silk-javafx:1.1.0 JAR provides a new Node class: griffon.javafx.support.silkicons.SilkIcon. You may use this class with any JavaFX control that accepts a graphic property. You may also use the icon directly as it is a subclass of javafx.scene.control.Label.

When I look at the source code for griffon.javafx.support.silkicons.SilkIcon it appears to extend Image rather than Node.  Is it possible to update the guide show an example that works with groovyfx 
e.g. 1. - does not work
                                button(text: "Sample", sampleAction) {
                                    graphic { silkIcon "star" }
                                }

e.g. 2. does not work

samples.SampleController.action.Sample.icon=griffon.javafx.support.silk.SilkIcon|star

**Comment by shnplr** [comment]
Found a solution for 1. by wrapping the image inside ImageView:

```
button(text: "Sample", sampleAction) {
    graphic { 
        imageView { silkIcon "star" }
    }
}
```

**Comment by aalmiray** [comment]
Indeed. The guide reflects the old API when the icon used to be a subclass of `Label`. It was changed to a subclass of `Image` for performance reasons. The workaround you found is the correct way to deal with this icon. I'll update the guide.

**Comment by aalmiray** [comment]
I believe the `ValueConversionException` occurs due to a bug in Griffon 2.3.0 that has been fixed in 2.4.0. Which version of Griffon are you running?

**Comment by shnplr** [comment]
Yes, I am running 2.4.0

griffon {
    disableDependencyResolution = false
    includeGroovyDependencies = true
    version = '2.4.0'
    toolkit = 'javafx'
}

**Comment by shnplr** [comment]
The underlying issue was ClassNotFoundException - after changing the package name used in messages.properties the error no longer occurs.

Fix Typo in:-
https://github.com/griffon-plugins/griffon-silkicons-plugin/blob/master/subprojects/griffon-silkicons-guide/src/asciidoc/usage.adoc

s/.support.silk/.support.silkicons/
